function initOrbs(){let wrap=document.getElementById('bg-orbs');if(!wrap){wrap=document.createElement('div');wrap.id='bg-orbs';document.body.prepend(wrap);}if(wrap.children.length)return;[{w:440,h:440,top:'-80px',left:'-60px',bg:'#1A3C6E',dur:'22s'},{w:300,h:300,top:'40%',right:'-80px',bg:'#1A5C35',dur:'28s',delay:'-8s'},{w:260,h:260,bottom:'-60px',left:'30%',bg:'#7A4A10',dur:'24s',delay:'-14s'}].forEach(c=>{const o=document.createElement('div');o.className='orb';o.style.cssText=`width:${c.w}px;height:${c.h}px;background:${c.bg};animation-duration:${c.dur};animation-delay:${c.delay||'0s'};${c.top?'top:'+c.top+';':''}${c.bottom?'bottom:'+c.bottom+';':''}${c.left?'left:'+c.left+';':''}${c.right?'right:'+c.right+';':''}`;wrap.appendChild(o);});}
function animateCounters(){document.querySelectorAll('.statv').forEach(el=>{const txt=el.textContent;const target=parseFloat(txt.replace('%','').replace(',','.'));if(isNaN(target)||target===0||el._animated===txt)return;el._animated=txt;const isFloat=txt.includes('.');const hasPct=txt.includes('%');const steps=45;let i=0;const iv=setInterval(()=>{i++;const p=1-Math.pow(1-i/steps,3);const v=target*p;el.textContent=(isFloat?v.toFixed(1):Math.round(v))+(hasPct?'%':'');if(i>=steps){el.textContent=txt;clearInterval(iv);}},700/steps);});}
function staggerRows(){document.querySelectorAll('.ri,.ann-it,.sch-it,.report-card,.qprev').forEach((el,i)=>{if(el._staggered)return;el._staggered=true;el.style.cssText+=`;opacity:0;transform:translateX(-10px)`;setTimeout(()=>{el.style.transition='opacity .3s ease, transform .3s ease';el.style.opacity='1';el.style.transform='none';},i*48);});}
function staggerStats(){document.querySelectorAll('.stat,.class-card,.sc').forEach((el,i)=>{if(el._staggered)return;el._staggered=true;el.style.cssText+=`;opacity:0;transform:translateY(14px) scale(.97)`;setTimeout(()=>{el.style.transition='opacity .38s ease, transform .38s cubic-bezier(.34,1.2,.64,1)';el.style.opacity='1';el.style.transform='none';},i*65);});}
function animateProgressBars(){document.querySelectorAll('.prog-fill,.ai-bar-fill').forEach(bar=>{if(bar._animated)return;bar._animated=true;const target=bar.style.width;bar.style.transition='none';bar.style.width='0';setTimeout(()=>{bar.style.transition='width 1s cubic-bezier(.4,0,.2,1)';bar.style.width=target;},90);});}
function initCardHovers(){document.querySelectorAll('.card:not(.card-hover),.class-card:not(.card-hover),.sc:not(.card-hover)').forEach(el=>{el.classList.add('card-hover');});}
function initScrollReveal(){if(!window._sro){window._sro=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');window._sro.unobserve(e.target);}});},{threshold:.12});}document.querySelectorAll('.reveal').forEach(el=>window._sro.observe(el));}
function initRipples(){document.querySelectorAll('.btn-p,.btn-s').forEach(btn=>{if(btn._ripple)return;btn._ripple=true;btn.addEventListener('click',e=>{const r=document.createElement('span');const rect=btn.getBoundingClientRect();const sz=Math.max(rect.width,rect.height)*2;r.style.cssText=`position:absolute;width:${sz}px;height:${sz}px;border-radius:50%;background:rgba(255,255,255,.22);transform:scale(0);top:${e.clientY-rect.top-sz/2}px;left:${e.clientX-rect.left-sz/2}px;pointer-events:none;animation:ripA .55s ease;z-index:10`;btn.appendChild(r);setTimeout(()=>r.remove(),560);});});}
let _tw=null;
function toast(msg,type='ok',dur=2800){if(!_tw){_tw=document.createElement('div');_tw.className='toast-wrap';document.body.appendChild(_tw);}const t=document.createElement('div');t.className=`toast toast-${type}`;t.innerHTML=`<span class="toast-icon">${{ok:'✓',warn:'⚠',err:'✕',info:'ℹ'}[type]||'ℹ'}</span><span>${msg}</span>`;_tw.appendChild(t);setTimeout(()=>{t.style.animation='toastOut .25s ease forwards';setTimeout(()=>t.remove(),260);},dur);}
function startClock(){const el=document.querySelector('[data-clock]');if(!el)return;const u=()=>el.textContent=new Date().toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'});u();clearInterval(window._ci);window._ci=setInterval(u,15000);}
function initLogoSpin(){const lm=document.querySelector('.slogo-mark');if(!lm||lm._spinBound)return;lm._spinBound=true;lm.style.cursor='pointer';lm.addEventListener('click',()=>{lm.style.transition='transform .5s cubic-bezier(.34,1.56,.64,1)';lm.style.transform='rotate(360deg) scale(1.2)';setTimeout(()=>{lm.style.transition='transform .4s ease';lm.style.transform='';},500);toast('Osvita — освітня платформа','info',1800);});}
if(!document.getElementById('anim-kf')){const s=document.createElement('style');s.id='anim-kf';s.textContent='@keyframes ripA{to{transform:scale(1);opacity:0}}@keyframes toastOut{to{opacity:0;transform:translateX(30px)}}@keyframes orbFloat{0%{transform:translate(0,0) scale(1)}33%{transform:translate(28px,-38px) scale(1.08)}66%{transform:translate(-18px,18px) scale(.93)}100%{transform:translate(0,0) scale(1)}}';document.head.appendChild(s);}
window.addEventListener('resize',()=>{
  if(S.menuOpen&&window.innerWidth>768){closeMenu();}
});
const _baseRender=render;
window.render=function(){
  _baseRender();
  requestAnimationFrame(()=>{
    initOrbs();initCardHovers();initRipples();startClock();initLogoSpin();
  });
};
render=window.render;
render();
